### PR TITLE
fix: added tusdt svg logo to dsmarttrader

### PR DESCRIPTION
**Pull request by henry-deriv**
Changes:

-   ...

## Type of change

-   [x] Bug fix
-   [ ] New feature
-   [ ] Update feature
-   [ ] Refactor code
-   [ ] Translation to code
-   [ ] Translation to crowdin
-   [ ] Script configuration
-   [ ] Improve performance
-   [ ] Style only
-   [ ] Dependency update
-   [ ] Documentation update
-   [ ] Release

### CODE REVIEW

**Review by niloofar-deriv — APPROVED** [review]
LGTM, Just a question, did you minify the SVG file using SVGO?

**Comment by henry-deriv** [comment]
> Visit Preview

package.json doesn't have command for svgo in this repo but I believe *npm run start* command runs SVGO.

**Comment by niloofar-deriv** [comment]
> > Visit Preview
> 
> package.json doesn't have command for svgo in this repo but I believe _npm run start_ command runs SVGO.

As far as I know we don't run it in `npm run start` command, we manually running svgo command in order to minify our svgs!
for doing that you need to install `npm -g install svgo` please following the [documentation](https://github.com/svg/svgo) :pray:
Also we don't need to install the svgo library in our project!

```
// Processing single files:
svgo one.svg two.svg -o one.min.svg two.min.svg
// Processing directory of svg files, recursively using `-f`, `--folder` :
svgo -f ./path/to/folder/with/svg/files -o ./path/to/folder/with/svg/output
```

**Comment by henry-deriv** [comment]
Ok will do! Is there a way to check which SVGs are minimized or not? One way I could think of is check file size but not sure.

**Comment by niloofar-deriv** [comment]
> Ok will do! Is there a way to check which SVGs are minimized or not? One way I could think of is check file size but not sure.

Yes you can check the size of the images!

**Comment by henry-deriv** [comment]
Checked. File size for newly added svg was same as others since it was a copy of existing svg file 😁

**Comment by niloofar-deriv** [comment]
> Checked. File size for newly added svg was same as others since it was a copy of existing svg file grin

Cool :grin::laughing: Thanks for checking

**Review by niloofar-deriv — APPROVED** [review]

**Review by matin-deriv — APPROVED** [review]

**Pull request closed without merging**
